### PR TITLE
Optionally create certificates just for subdomains

### PR DESCRIPTION
**Pull request by stuwil**
Added an ONLY_SUBDOMAIN env variable that can be set to true, when only subdomain certificates are needed.

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks stuwil, I'll review the code when I get a chance. But what's the use case here? Why would you want a cert that covers only the subdomains and not the domain?

If letsencrypt allowed it, I would do wildcard certs that cover the domain and all the subdomains because it is a pain to add more later

**Comment by stuwil** [comment]
Hi aptalca,

Might be a limited use case, but in my instance, the web server for the domain is actually on a separate box - the nginx docker/subdomains are living in unRAID. Perhaps another approach would be to just take in a comma separated list of fully qualified domain names?

**Comment by miketweaver** [comment]
I've run into the same issue as @stuwil here. Thanks for the pull request, as it has allowed me to secure just subdomains. My root domain lives on a small vps in a datacenter, but I still needed these subdomains secured on my UnRaid at home.

**Comment by aptalca** [comment]
Thanks for the PR. I since changed the cert retrieval/renewal method so I won't be merging this, but I will incorporate this feature soon.

**Comment by aptalca** [comment]
Well, there is one issue with this whole thing.

Letsencrypt by default puts the certs in a folder named "domain.url"

This container links to that folder for the certs.

If you only have a few subdomains and no actual domain, I'm not sure what folder it will use. Perhaps the name of the first subdomain listed? subdomain1.domain.url?? I'm not sure

That's why I'm currently separating out the url and the subdomains so I can figure out the folder location for the certs created.

Unfortunately letsencrypt isn't that great for automation yet. It doesn't even let you specify which folder the certs should be put in (there are a lot of feature requests for that)

I'll have to think about that more and do some testing

**Comment by stuwil** [comment]
Sorry for the delay, missed this. If there's no domain specified (just subdomains), it goes with the first subdomain specified. Check commit a2e5a5bcf8c6306e7f988dd14bca8bae7ca82467 for how I was handling this.

Let me know if you're still interested in eventually merging something like this, and I can probably adjust the PR to recent master changes.

**Comment by aptalca** [comment]
Hi stuwil,

This branch is stale due to many updates to the master.

However, I added in the support for "only subdomain" certs in a new dev branch. Thanks so much for your code contribution, it was very helpful as a reference. 

Could you test the dev version before I merge it with the master?

The branch here is called "dev" and the docker build is here: https://hub.docker.com/r/aptalca/nginx-letsencrypt-dev/

Thanks

**Comment by aptalca** [comment]
Closing this due to conflicts with the master branch, but the only subdomains feature has been incorporated into master

**Pull request closed without merging**
